services:

  mongo:
    image: mongo:6
    
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 40s

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://mongo:27017/clothingstore

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend