sonar.projectKey=online-clothing-store
sonar.projectName=online-clothing-store
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.login=sqa_0f12922c95892f7bb4e0ee6bad82e6c15c5ae56d